// Code generated by ent, DO NOT EDIT.

package application

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the application type in the database.
	Label = "application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldClientSecretHash holds the string denoting the client_secret_hash field in the database.
	FieldClientSecretHash = "client_secret_hash"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRedirectUris holds the string denoting the redirect_uris field in the database.
	FieldRedirectUris = "redirect_uris"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldGrantTypes holds the string denoting the grant_types field in the database.
	FieldGrantTypes = "grant_types"
	// FieldApplicationType holds the string denoting the application_type field in the database.
	FieldApplicationType = "application_type"
	// FieldAccessTokenType holds the string denoting the access_token_type field in the database.
	FieldAccessTokenType = "access_token_type"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldIDTokenLifetime holds the string denoting the id_token_lifetime field in the database.
	FieldIDTokenLifetime = "id_token_lifetime"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the application in the database.
	Table = "applications"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "applications"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
)

// Columns holds all SQL columns for application fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldClientID,
	FieldClientSecretHash,
	FieldName,
	FieldRedirectUris,
	FieldScopes,
	FieldGrantTypes,
	FieldApplicationType,
	FieldAccessTokenType,
	FieldTenantID,
	FieldIDTokenLifetime,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// ClientSecretHashValidator is a validator for the "client_secret_hash" field. It is called by the builders before save.
	ClientSecretHashValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultApplicationType holds the default value on creation for the "application_type" field.
	DefaultApplicationType string
	// ApplicationTypeValidator is a validator for the "application_type" field. It is called by the builders before save.
	ApplicationTypeValidator func(string) error
	// DefaultAccessTokenType holds the default value on creation for the "access_token_type" field.
	DefaultAccessTokenType string
	// AccessTokenTypeValidator is a validator for the "access_token_type" field. It is called by the builders before save.
	AccessTokenTypeValidator func(string) error
	// DefaultIDTokenLifetime holds the default value on creation for the "id_token_lifetime" field.
	DefaultIDTokenLifetime int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Application queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByClientSecretHash orders the results by the client_secret_hash field.
func ByClientSecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSecretHash, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByApplicationType orders the results by the application_type field.
func ByApplicationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationType, opts...).ToFunc()
}

// ByAccessTokenType orders the results by the access_token_type field.
func ByAccessTokenType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenType, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByIDTokenLifetime orders the results by the id_token_lifetime field.
func ByIDTokenLifetime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDTokenLifetime, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
