// Code generated by ent, DO NOT EDIT.

package application

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldDeletedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientID, v))
}

// ClientSecretHash applies equality check predicate on the "client_secret_hash" field. It's identical to ClientSecretHashEQ.
func ClientSecretHash(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientSecretHash, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldName, v))
}

// ApplicationType applies equality check predicate on the "application_type" field. It's identical to ApplicationTypeEQ.
func ApplicationType(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldApplicationType, v))
}

// AccessTokenType applies equality check predicate on the "access_token_type" field. It's identical to AccessTokenTypeEQ.
func AccessTokenType(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldAccessTokenType, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldTenantID, v))
}

// IDTokenLifetime applies equality check predicate on the "id_token_lifetime" field. It's identical to IDTokenLifetimeEQ.
func IDTokenLifetime(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldIDTokenLifetime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Application {
	return predicate.Application(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Application {
	return predicate.Application(sql.FieldNotNull(FieldDeletedAt))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretHashEQ applies the EQ predicate on the "client_secret_hash" field.
func ClientSecretHashEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientSecretHashNEQ applies the NEQ predicate on the "client_secret_hash" field.
func ClientSecretHashNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldClientSecretHash, v))
}

// ClientSecretHashIn applies the In predicate on the "client_secret_hash" field.
func ClientSecretHashIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashNotIn applies the NotIn predicate on the "client_secret_hash" field.
func ClientSecretHashNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashGT applies the GT predicate on the "client_secret_hash" field.
func ClientSecretHashGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldClientSecretHash, v))
}

// ClientSecretHashGTE applies the GTE predicate on the "client_secret_hash" field.
func ClientSecretHashGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldClientSecretHash, v))
}

// ClientSecretHashLT applies the LT predicate on the "client_secret_hash" field.
func ClientSecretHashLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldClientSecretHash, v))
}

// ClientSecretHashLTE applies the LTE predicate on the "client_secret_hash" field.
func ClientSecretHashLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldClientSecretHash, v))
}

// ClientSecretHashContains applies the Contains predicate on the "client_secret_hash" field.
func ClientSecretHashContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldClientSecretHash, v))
}

// ClientSecretHashHasPrefix applies the HasPrefix predicate on the "client_secret_hash" field.
func ClientSecretHashHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldClientSecretHash, v))
}

// ClientSecretHashHasSuffix applies the HasSuffix predicate on the "client_secret_hash" field.
func ClientSecretHashHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldClientSecretHash, v))
}

// ClientSecretHashEqualFold applies the EqualFold predicate on the "client_secret_hash" field.
func ClientSecretHashEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldClientSecretHash, v))
}

// ClientSecretHashContainsFold applies the ContainsFold predicate on the "client_secret_hash" field.
func ClientSecretHashContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldClientSecretHash, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldName, v))
}

// ApplicationTypeEQ applies the EQ predicate on the "application_type" field.
func ApplicationTypeEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldApplicationType, v))
}

// ApplicationTypeNEQ applies the NEQ predicate on the "application_type" field.
func ApplicationTypeNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldApplicationType, v))
}

// ApplicationTypeIn applies the In predicate on the "application_type" field.
func ApplicationTypeIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldApplicationType, vs...))
}

// ApplicationTypeNotIn applies the NotIn predicate on the "application_type" field.
func ApplicationTypeNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldApplicationType, vs...))
}

// ApplicationTypeGT applies the GT predicate on the "application_type" field.
func ApplicationTypeGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldApplicationType, v))
}

// ApplicationTypeGTE applies the GTE predicate on the "application_type" field.
func ApplicationTypeGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldApplicationType, v))
}

// ApplicationTypeLT applies the LT predicate on the "application_type" field.
func ApplicationTypeLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldApplicationType, v))
}

// ApplicationTypeLTE applies the LTE predicate on the "application_type" field.
func ApplicationTypeLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldApplicationType, v))
}

// ApplicationTypeContains applies the Contains predicate on the "application_type" field.
func ApplicationTypeContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldApplicationType, v))
}

// ApplicationTypeHasPrefix applies the HasPrefix predicate on the "application_type" field.
func ApplicationTypeHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldApplicationType, v))
}

// ApplicationTypeHasSuffix applies the HasSuffix predicate on the "application_type" field.
func ApplicationTypeHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldApplicationType, v))
}

// ApplicationTypeEqualFold applies the EqualFold predicate on the "application_type" field.
func ApplicationTypeEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldApplicationType, v))
}

// ApplicationTypeContainsFold applies the ContainsFold predicate on the "application_type" field.
func ApplicationTypeContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldApplicationType, v))
}

// AccessTokenTypeEQ applies the EQ predicate on the "access_token_type" field.
func AccessTokenTypeEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldAccessTokenType, v))
}

// AccessTokenTypeNEQ applies the NEQ predicate on the "access_token_type" field.
func AccessTokenTypeNEQ(v string) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldAccessTokenType, v))
}

// AccessTokenTypeIn applies the In predicate on the "access_token_type" field.
func AccessTokenTypeIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldAccessTokenType, vs...))
}

// AccessTokenTypeNotIn applies the NotIn predicate on the "access_token_type" field.
func AccessTokenTypeNotIn(vs ...string) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldAccessTokenType, vs...))
}

// AccessTokenTypeGT applies the GT predicate on the "access_token_type" field.
func AccessTokenTypeGT(v string) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldAccessTokenType, v))
}

// AccessTokenTypeGTE applies the GTE predicate on the "access_token_type" field.
func AccessTokenTypeGTE(v string) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldAccessTokenType, v))
}

// AccessTokenTypeLT applies the LT predicate on the "access_token_type" field.
func AccessTokenTypeLT(v string) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldAccessTokenType, v))
}

// AccessTokenTypeLTE applies the LTE predicate on the "access_token_type" field.
func AccessTokenTypeLTE(v string) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldAccessTokenType, v))
}

// AccessTokenTypeContains applies the Contains predicate on the "access_token_type" field.
func AccessTokenTypeContains(v string) predicate.Application {
	return predicate.Application(sql.FieldContains(FieldAccessTokenType, v))
}

// AccessTokenTypeHasPrefix applies the HasPrefix predicate on the "access_token_type" field.
func AccessTokenTypeHasPrefix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasPrefix(FieldAccessTokenType, v))
}

// AccessTokenTypeHasSuffix applies the HasSuffix predicate on the "access_token_type" field.
func AccessTokenTypeHasSuffix(v string) predicate.Application {
	return predicate.Application(sql.FieldHasSuffix(FieldAccessTokenType, v))
}

// AccessTokenTypeEqualFold applies the EqualFold predicate on the "access_token_type" field.
func AccessTokenTypeEqualFold(v string) predicate.Application {
	return predicate.Application(sql.FieldEqualFold(FieldAccessTokenType, v))
}

// AccessTokenTypeContainsFold applies the ContainsFold predicate on the "access_token_type" field.
func AccessTokenTypeContainsFold(v string) predicate.Application {
	return predicate.Application(sql.FieldContainsFold(FieldAccessTokenType, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldTenantID, vs...))
}

// IDTokenLifetimeEQ applies the EQ predicate on the "id_token_lifetime" field.
func IDTokenLifetimeEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldIDTokenLifetime, v))
}

// IDTokenLifetimeNEQ applies the NEQ predicate on the "id_token_lifetime" field.
func IDTokenLifetimeNEQ(v int) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldIDTokenLifetime, v))
}

// IDTokenLifetimeIn applies the In predicate on the "id_token_lifetime" field.
func IDTokenLifetimeIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldIDTokenLifetime, vs...))
}

// IDTokenLifetimeNotIn applies the NotIn predicate on the "id_token_lifetime" field.
func IDTokenLifetimeNotIn(vs ...int) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldIDTokenLifetime, vs...))
}

// IDTokenLifetimeGT applies the GT predicate on the "id_token_lifetime" field.
func IDTokenLifetimeGT(v int) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldIDTokenLifetime, v))
}

// IDTokenLifetimeGTE applies the GTE predicate on the "id_token_lifetime" field.
func IDTokenLifetimeGTE(v int) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldIDTokenLifetime, v))
}

// IDTokenLifetimeLT applies the LT predicate on the "id_token_lifetime" field.
func IDTokenLifetimeLT(v int) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldIDTokenLifetime, v))
}

// IDTokenLifetimeLTE applies the LTE predicate on the "id_token_lifetime" field.
func IDTokenLifetimeLTE(v int) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldIDTokenLifetime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Application {
	return predicate.Application(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Application {
	return predicate.Application(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Application {
	return predicate.Application(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Application) predicate.Application {
	return predicate.Application(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Application) predicate.Application {
	return predicate.Application(sql.NotPredicates(p))
}
