FROM golang:1.26.1-alpine AS builder

RUN apk add --no-cache git bash ca-certificates tzdata

RUN go install github.com/air-verse/air@latest

ENV PATH="/go/bin:${PATH}"
WORKDIR /workspace

CMD ["air", "-c", ".air.toml"]
