services:
  audit:
    container_name: audit
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile.air
    working_dir: /workspace/app/audit/service
    command: ["air", "-c", ".air.toml"]
    environment:
      TZ: Asia/Shanghai
      GOMODCACHE: /go/pkg/mod
      GOCACHE: /go/cache
    volumes:
      - ./:/workspace
      - ./.cache/go-mod:/go/pkg/mod
      - ./.cache/go-build:/go/cache
      - ./app/audit/service/configs/docker/:/app/configs/
      - audit-logs:/app/logs
    ports:
      - "10000:8000"
      - "10001:8001"
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - servora-network

volumes:
  audit-logs:
