// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/application"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenant"
	"github.com/google/uuid"
)

// ApplicationCreate is the builder for creating a Application entity.
type ApplicationCreate struct {
	config
	mutation *ApplicationMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ApplicationCreate) SetDeletedAt(v time.Time) *ApplicationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableDeletedAt(v *time.Time) *ApplicationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ApplicationCreate) SetClientID(v string) *ApplicationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *ApplicationCreate) SetClientSecretHash(v string) *ApplicationCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ApplicationCreate) SetName(v string) *ApplicationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *ApplicationCreate) SetRedirectUris(v []string) *ApplicationCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *ApplicationCreate) SetScopes(v []string) *ApplicationCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetGrantTypes sets the "grant_types" field.
func (_c *ApplicationCreate) SetGrantTypes(v []string) *ApplicationCreate {
	_c.mutation.SetGrantTypes(v)
	return _c
}

// SetApplicationType sets the "application_type" field.
func (_c *ApplicationCreate) SetApplicationType(v string) *ApplicationCreate {
	_c.mutation.SetApplicationType(v)
	return _c
}

// SetNillableApplicationType sets the "application_type" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableApplicationType(v *string) *ApplicationCreate {
	if v != nil {
		_c.SetApplicationType(*v)
	}
	return _c
}

// SetAccessTokenType sets the "access_token_type" field.
func (_c *ApplicationCreate) SetAccessTokenType(v string) *ApplicationCreate {
	_c.mutation.SetAccessTokenType(v)
	return _c
}

// SetNillableAccessTokenType sets the "access_token_type" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableAccessTokenType(v *string) *ApplicationCreate {
	if v != nil {
		_c.SetAccessTokenType(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ApplicationCreate) SetTenantID(v uuid.UUID) *ApplicationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetIDTokenLifetime sets the "id_token_lifetime" field.
func (_c *ApplicationCreate) SetIDTokenLifetime(v int) *ApplicationCreate {
	_c.mutation.SetIDTokenLifetime(v)
	return _c
}

// SetNillableIDTokenLifetime sets the "id_token_lifetime" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableIDTokenLifetime(v *int) *ApplicationCreate {
	if v != nil {
		_c.SetIDTokenLifetime(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApplicationCreate) SetCreatedAt(v time.Time) *ApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableCreatedAt(v *time.Time) *ApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApplicationCreate) SetUpdatedAt(v time.Time) *ApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableUpdatedAt(v *time.Time) *ApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ApplicationCreate) SetID(v uuid.UUID) *ApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ApplicationCreate) SetNillableID(v *uuid.UUID) *ApplicationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ApplicationCreate) SetTenant(v *Tenant) *ApplicationCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the ApplicationMutation object of the builder.
func (_c *ApplicationCreate) Mutation() *ApplicationMutation {
	return _c.mutation
}

// Save creates the Application in the database.
func (_c *ApplicationCreate) Save(ctx context.Context) (*Application, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApplicationCreate) SaveX(ctx context.Context) *Application {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApplicationCreate) defaults() {
	if _, ok := _c.mutation.ApplicationType(); !ok {
		v := application.DefaultApplicationType
		_c.mutation.SetApplicationType(v)
	}
	if _, ok := _c.mutation.AccessTokenType(); !ok {
		v := application.DefaultAccessTokenType
		_c.mutation.SetAccessTokenType(v)
	}
	if _, ok := _c.mutation.IDTokenLifetime(); !ok {
		v := application.DefaultIDTokenLifetime
		_c.mutation.SetIDTokenLifetime(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := application.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := application.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := application.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApplicationCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Application.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := application.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Application.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecretHash(); !ok {
		return &ValidationError{Name: "client_secret_hash", err: errors.New(`ent: missing required field "Application.client_secret_hash"`)}
	}
	if v, ok := _c.mutation.ClientSecretHash(); ok {
		if err := application.ClientSecretHashValidator(v); err != nil {
			return &ValidationError{Name: "client_secret_hash", err: fmt.Errorf(`ent: validator failed for field "Application.client_secret_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Application.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectUris(); !ok {
		return &ValidationError{Name: "redirect_uris", err: errors.New(`ent: missing required field "Application.redirect_uris"`)}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "Application.scopes"`)}
	}
	if _, ok := _c.mutation.GrantTypes(); !ok {
		return &ValidationError{Name: "grant_types", err: errors.New(`ent: missing required field "Application.grant_types"`)}
	}
	if _, ok := _c.mutation.ApplicationType(); !ok {
		return &ValidationError{Name: "application_type", err: errors.New(`ent: missing required field "Application.application_type"`)}
	}
	if v, ok := _c.mutation.ApplicationType(); ok {
		if err := application.ApplicationTypeValidator(v); err != nil {
			return &ValidationError{Name: "application_type", err: fmt.Errorf(`ent: validator failed for field "Application.application_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessTokenType(); !ok {
		return &ValidationError{Name: "access_token_type", err: errors.New(`ent: missing required field "Application.access_token_type"`)}
	}
	if v, ok := _c.mutation.AccessTokenType(); ok {
		if err := application.AccessTokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "access_token_type", err: fmt.Errorf(`ent: validator failed for field "Application.access_token_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Application.tenant_id"`)}
	}
	if _, ok := _c.mutation.IDTokenLifetime(); !ok {
		return &ValidationError{Name: "id_token_lifetime", err: errors.New(`ent: missing required field "Application.id_token_lifetime"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Application.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Application.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Application.tenant"`)}
	}
	return nil
}

func (_c *ApplicationCreate) sqlSave(ctx context.Context) (*Application, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApplicationCreate) createSpec() (*Application, *sqlgraph.CreateSpec) {
	var (
		_node = &Application{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(application.Table, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(application.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(application.FieldClientSecretHash, field.TypeString, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(application.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(application.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.GrantTypes(); ok {
		_spec.SetField(application.FieldGrantTypes, field.TypeJSON, value)
		_node.GrantTypes = value
	}
	if value, ok := _c.mutation.ApplicationType(); ok {
		_spec.SetField(application.FieldApplicationType, field.TypeString, value)
		_node.ApplicationType = value
	}
	if value, ok := _c.mutation.AccessTokenType(); ok {
		_spec.SetField(application.FieldAccessTokenType, field.TypeString, value)
		_node.AccessTokenType = value
	}
	if value, ok := _c.mutation.IDTokenLifetime(); ok {
		_spec.SetField(application.FieldIDTokenLifetime, field.TypeInt, value)
		_node.IDTokenLifetime = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(application.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   application.TenantTable,
			Columns: []string{application.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ApplicationCreateBulk is the builder for creating many Application entities in bulk.
type ApplicationCreateBulk struct {
	config
	err      error
	builders []*ApplicationCreate
}

// Save creates the Application entities in the database.
func (_c *ApplicationCreateBulk) Save(ctx context.Context) ([]*Application, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Application, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApplicationCreateBulk) SaveX(ctx context.Context) []*Application {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
