// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/application"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/predicate"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenant"
	"github.com/google/uuid"
)

// ApplicationUpdate is the builder for updating Application entities.
type ApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationMutation
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (_u *ApplicationUpdate) Where(ps ...predicate.Application) *ApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApplicationUpdate) SetDeletedAt(v time.Time) *ApplicationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableDeletedAt(v *time.Time) *ApplicationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApplicationUpdate) ClearDeletedAt() *ApplicationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ApplicationUpdate) SetClientID(v string) *ApplicationUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableClientID(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *ApplicationUpdate) SetClientSecretHash(v string) *ApplicationUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableClientSecretHash(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApplicationUpdate) SetName(v string) *ApplicationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableName(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *ApplicationUpdate) SetRedirectUris(v []string) *ApplicationUpdate {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *ApplicationUpdate) AppendRedirectUris(v []string) *ApplicationUpdate {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *ApplicationUpdate) SetScopes(v []string) *ApplicationUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *ApplicationUpdate) AppendScopes(v []string) *ApplicationUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *ApplicationUpdate) SetGrantTypes(v []string) *ApplicationUpdate {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *ApplicationUpdate) AppendGrantTypes(v []string) *ApplicationUpdate {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetApplicationType sets the "application_type" field.
func (_u *ApplicationUpdate) SetApplicationType(v string) *ApplicationUpdate {
	_u.mutation.SetApplicationType(v)
	return _u
}

// SetNillableApplicationType sets the "application_type" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableApplicationType(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetApplicationType(*v)
	}
	return _u
}

// SetAccessTokenType sets the "access_token_type" field.
func (_u *ApplicationUpdate) SetAccessTokenType(v string) *ApplicationUpdate {
	_u.mutation.SetAccessTokenType(v)
	return _u
}

// SetNillableAccessTokenType sets the "access_token_type" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableAccessTokenType(v *string) *ApplicationUpdate {
	if v != nil {
		_u.SetAccessTokenType(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ApplicationUpdate) SetTenantID(v uuid.UUID) *ApplicationUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableTenantID(v *uuid.UUID) *ApplicationUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetIDTokenLifetime sets the "id_token_lifetime" field.
func (_u *ApplicationUpdate) SetIDTokenLifetime(v int) *ApplicationUpdate {
	_u.mutation.ResetIDTokenLifetime()
	_u.mutation.SetIDTokenLifetime(v)
	return _u
}

// SetNillableIDTokenLifetime sets the "id_token_lifetime" field if the given value is not nil.
func (_u *ApplicationUpdate) SetNillableIDTokenLifetime(v *int) *ApplicationUpdate {
	if v != nil {
		_u.SetIDTokenLifetime(*v)
	}
	return _u
}

// AddIDTokenLifetime adds value to the "id_token_lifetime" field.
func (_u *ApplicationUpdate) AddIDTokenLifetime(v int) *ApplicationUpdate {
	_u.mutation.AddIDTokenLifetime(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApplicationUpdate) SetUpdatedAt(v time.Time) *ApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ApplicationUpdate) SetTenant(v *Tenant) *ApplicationUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the ApplicationMutation object of the builder.
func (_u *ApplicationUpdate) Mutation() *ApplicationMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ApplicationUpdate) ClearTenant() *ApplicationUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := application.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApplicationUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := application.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Application.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientSecretHash(); ok {
		if err := application.ClientSecretHashValidator(v); err != nil {
			return &ValidationError{Name: "client_secret_hash", err: fmt.Errorf(`ent: validator failed for field "Application.client_secret_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ApplicationType(); ok {
		if err := application.ApplicationTypeValidator(v); err != nil {
			return &ValidationError{Name: "application_type", err: fmt.Errorf(`ent: validator failed for field "Application.application_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessTokenType(); ok {
		if err := application.AccessTokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "access_token_type", err: fmt.Errorf(`ent: validator failed for field "Application.access_token_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Application.tenant"`)
	}
	return nil
}

func (_u *ApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(application.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(application.FieldClientSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(application.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(application.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(application.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.ApplicationType(); ok {
		_spec.SetField(application.FieldApplicationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenType(); ok {
		_spec.SetField(application.FieldAccessTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDTokenLifetime(); ok {
		_spec.SetField(application.FieldIDTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenLifetime(); ok {
		_spec.AddField(application.FieldIDTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   application.TenantTable,
			Columns: []string{application.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   application.TenantTable,
			Columns: []string{application.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApplicationUpdateOne is the builder for updating a single Application entity.
type ApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ApplicationUpdateOne) SetDeletedAt(v time.Time) *ApplicationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableDeletedAt(v *time.Time) *ApplicationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ApplicationUpdateOne) ClearDeletedAt() *ApplicationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ApplicationUpdateOne) SetClientID(v string) *ApplicationUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableClientID(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *ApplicationUpdateOne) SetClientSecretHash(v string) *ApplicationUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableClientSecretHash(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApplicationUpdateOne) SetName(v string) *ApplicationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableName(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *ApplicationUpdateOne) SetRedirectUris(v []string) *ApplicationUpdateOne {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *ApplicationUpdateOne) AppendRedirectUris(v []string) *ApplicationUpdateOne {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *ApplicationUpdateOne) SetScopes(v []string) *ApplicationUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *ApplicationUpdateOne) AppendScopes(v []string) *ApplicationUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *ApplicationUpdateOne) SetGrantTypes(v []string) *ApplicationUpdateOne {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *ApplicationUpdateOne) AppendGrantTypes(v []string) *ApplicationUpdateOne {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetApplicationType sets the "application_type" field.
func (_u *ApplicationUpdateOne) SetApplicationType(v string) *ApplicationUpdateOne {
	_u.mutation.SetApplicationType(v)
	return _u
}

// SetNillableApplicationType sets the "application_type" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableApplicationType(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetApplicationType(*v)
	}
	return _u
}

// SetAccessTokenType sets the "access_token_type" field.
func (_u *ApplicationUpdateOne) SetAccessTokenType(v string) *ApplicationUpdateOne {
	_u.mutation.SetAccessTokenType(v)
	return _u
}

// SetNillableAccessTokenType sets the "access_token_type" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableAccessTokenType(v *string) *ApplicationUpdateOne {
	if v != nil {
		_u.SetAccessTokenType(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ApplicationUpdateOne) SetTenantID(v uuid.UUID) *ApplicationUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableTenantID(v *uuid.UUID) *ApplicationUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetIDTokenLifetime sets the "id_token_lifetime" field.
func (_u *ApplicationUpdateOne) SetIDTokenLifetime(v int) *ApplicationUpdateOne {
	_u.mutation.ResetIDTokenLifetime()
	_u.mutation.SetIDTokenLifetime(v)
	return _u
}

// SetNillableIDTokenLifetime sets the "id_token_lifetime" field if the given value is not nil.
func (_u *ApplicationUpdateOne) SetNillableIDTokenLifetime(v *int) *ApplicationUpdateOne {
	if v != nil {
		_u.SetIDTokenLifetime(*v)
	}
	return _u
}

// AddIDTokenLifetime adds value to the "id_token_lifetime" field.
func (_u *ApplicationUpdateOne) AddIDTokenLifetime(v int) *ApplicationUpdateOne {
	_u.mutation.AddIDTokenLifetime(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApplicationUpdateOne) SetUpdatedAt(v time.Time) *ApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ApplicationUpdateOne) SetTenant(v *Tenant) *ApplicationUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the ApplicationMutation object of the builder.
func (_u *ApplicationUpdateOne) Mutation() *ApplicationMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ApplicationUpdateOne) ClearTenant() *ApplicationUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the ApplicationUpdate builder.
func (_u *ApplicationUpdateOne) Where(ps ...predicate.Application) *ApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApplicationUpdateOne) Select(field string, fields ...string) *ApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Application entity.
func (_u *ApplicationUpdateOne) Save(ctx context.Context) (*Application, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApplicationUpdateOne) SaveX(ctx context.Context) *Application {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := application.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := application.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "Application.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientSecretHash(); ok {
		if err := application.ClientSecretHashValidator(v); err != nil {
			return &ValidationError{Name: "client_secret_hash", err: fmt.Errorf(`ent: validator failed for field "Application.client_secret_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := application.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Application.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ApplicationType(); ok {
		if err := application.ApplicationTypeValidator(v); err != nil {
			return &ValidationError{Name: "application_type", err: fmt.Errorf(`ent: validator failed for field "Application.application_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessTokenType(); ok {
		if err := application.AccessTokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "access_token_type", err: fmt.Errorf(`ent: validator failed for field "Application.access_token_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Application.tenant"`)
	}
	return nil
}

func (_u *ApplicationUpdateOne) sqlSave(ctx context.Context) (_node *Application, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(application.Table, application.Columns, sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Application.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, application.FieldID)
		for _, f := range fields {
			if !application.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != application.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(application.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(application.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(application.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(application.FieldClientSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(application.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(application.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(application.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(application.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, application.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.ApplicationType(); ok {
		_spec.SetField(application.FieldApplicationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenType(); ok {
		_spec.SetField(application.FieldAccessTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDTokenLifetime(); ok {
		_spec.SetField(application.FieldIDTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenLifetime(); ok {
		_spec.AddField(application.FieldIDTokenLifetime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(application.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   application.TenantTable,
			Columns: []string{application.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   application.TenantTable,
			Columns: []string{application.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Application{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{application.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
