// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/application"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/organization"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/organizationmember"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenant"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/tenantmember"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/ent/user"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescClientID is the schema descriptor for client_id field.
	applicationDescClientID := applicationFields[1].Descriptor()
	// application.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	application.ClientIDValidator = applicationDescClientID.Validators[0].(func(string) error)
	// applicationDescClientSecretHash is the schema descriptor for client_secret_hash field.
	applicationDescClientSecretHash := applicationFields[2].Descriptor()
	// application.ClientSecretHashValidator is a validator for the "client_secret_hash" field. It is called by the builders before save.
	application.ClientSecretHashValidator = applicationDescClientSecretHash.Validators[0].(func(string) error)
	// applicationDescName is the schema descriptor for name field.
	applicationDescName := applicationFields[3].Descriptor()
	// application.NameValidator is a validator for the "name" field. It is called by the builders before save.
	application.NameValidator = applicationDescName.Validators[0].(func(string) error)
	// applicationDescApplicationType is the schema descriptor for application_type field.
	applicationDescApplicationType := applicationFields[7].Descriptor()
	// application.DefaultApplicationType holds the default value on creation for the application_type field.
	application.DefaultApplicationType = applicationDescApplicationType.Default.(string)
	// application.ApplicationTypeValidator is a validator for the "application_type" field. It is called by the builders before save.
	application.ApplicationTypeValidator = applicationDescApplicationType.Validators[0].(func(string) error)
	// applicationDescAccessTokenType is the schema descriptor for access_token_type field.
	applicationDescAccessTokenType := applicationFields[8].Descriptor()
	// application.DefaultAccessTokenType holds the default value on creation for the access_token_type field.
	application.DefaultAccessTokenType = applicationDescAccessTokenType.Default.(string)
	// application.AccessTokenTypeValidator is a validator for the "access_token_type" field. It is called by the builders before save.
	application.AccessTokenTypeValidator = applicationDescAccessTokenType.Validators[0].(func(string) error)
	// applicationDescIDTokenLifetime is the schema descriptor for id_token_lifetime field.
	applicationDescIDTokenLifetime := applicationFields[10].Descriptor()
	// application.DefaultIDTokenLifetime holds the default value on creation for the id_token_lifetime field.
	application.DefaultIDTokenLifetime = applicationDescIDTokenLifetime.Default.(int)
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationFields[11].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationFields[12].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// applicationDescID is the schema descriptor for id field.
	applicationDescID := applicationFields[0].Descriptor()
	// application.DefaultID holds the default value on creation for the id field.
	application.DefaultID = applicationDescID.Default.(func() uuid.UUID)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[2].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[3].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescDisplayName is the schema descriptor for display_name field.
	organizationDescDisplayName := organizationFields[4].Descriptor()
	// organization.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	organization.DisplayNameValidator = organizationDescDisplayName.Validators[0].(func(string) error)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[5].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationFields[6].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	organizationmemberFields := schema.OrganizationMember{}.Fields()
	_ = organizationmemberFields
	// organizationmemberDescRole is the schema descriptor for role field.
	organizationmemberDescRole := organizationmemberFields[3].Descriptor()
	// organizationmember.DefaultRole holds the default value on creation for the role field.
	organizationmember.DefaultRole = organizationmemberDescRole.Default.(string)
	// organizationmember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	organizationmember.RoleValidator = organizationmemberDescRole.Validators[0].(func(string) error)
	// organizationmemberDescCreatedAt is the schema descriptor for created_at field.
	organizationmemberDescCreatedAt := organizationmemberFields[5].Descriptor()
	// organizationmember.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationmember.DefaultCreatedAt = organizationmemberDescCreatedAt.Default.(func() time.Time)
	// organizationmemberDescUpdatedAt is the schema descriptor for updated_at field.
	organizationmemberDescUpdatedAt := organizationmemberFields[6].Descriptor()
	// organizationmember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organizationmember.DefaultUpdatedAt = organizationmemberDescUpdatedAt.Default.(func() time.Time)
	// organizationmember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organizationmember.UpdateDefaultUpdatedAt = organizationmemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationmemberDescID is the schema descriptor for id field.
	organizationmemberDescID := organizationmemberFields[0].Descriptor()
	// organizationmember.DefaultID holds the default value on creation for the id field.
	organizationmember.DefaultID = organizationmemberDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[1].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[2].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescDisplayName is the schema descriptor for display_name field.
	tenantDescDisplayName := tenantFields[3].Descriptor()
	// tenant.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	tenant.DisplayNameValidator = tenantDescDisplayName.Validators[0].(func(string) error)
	// tenantDescDomain is the schema descriptor for domain field.
	tenantDescDomain := tenantFields[5].Descriptor()
	// tenant.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	tenant.DomainValidator = tenantDescDomain.Validators[0].(func(string) error)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[7].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[8].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantmemberFields := schema.TenantMember{}.Fields()
	_ = tenantmemberFields
	// tenantmemberDescCreatedAt is the schema descriptor for created_at field.
	tenantmemberDescCreatedAt := tenantmemberFields[6].Descriptor()
	// tenantmember.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantmember.DefaultCreatedAt = tenantmemberDescCreatedAt.Default.(func() time.Time)
	// tenantmemberDescUpdatedAt is the schema descriptor for updated_at field.
	tenantmemberDescUpdatedAt := tenantmemberFields[7].Descriptor()
	// tenantmember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantmember.DefaultUpdatedAt = tenantmemberDescUpdatedAt.Default.(func() time.Time)
	// tenantmember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantmember.UpdateDefaultUpdatedAt = tenantmemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantmemberDescID is the schema descriptor for id field.
	tenantmemberDescID := tenantmemberFields[0].Descriptor()
	// tenantmember.DefaultID holds the default value on creation for the id field.
	tenantmember.DefaultID = tenantmemberDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[5].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
