// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Servora-Kit/plateau/api/gen/go/audit/service/conf/v1"
	"github.com/Servora-Kit/plateau/api/gen/go/plateau/infra/clickhouse/v1"
	"github.com/Servora-Kit/plateau/app/audit/service/internal/biz"
	"github.com/Servora-Kit/plateau/app/audit/service/internal/data"
	"github.com/Servora-Kit/plateau/app/audit/service/internal/server"
	"github.com/Servora-Kit/plateau/app/audit/service/internal/service"
	"github.com/Servora-Kit/servora/api/gen/go/servora/contrib/kafka/v1"
	"github.com/Servora-Kit/servora/api/gen/go/servora/obs/audit/v1"
	"github.com/Servora-Kit/servora/contrib/kafka"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/Servora-Kit/servora/obs/metrics"
	"github.com/go-kratos/kratos/v3"
	"github.com/twmb/franz-go/pkg/kgo"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(runtime *bootstrap.Runtime, kafka *kafkapb.Kafka, clickHouse *clickhousepb.ClickHouse, auditContract *auditconfpb.AuditContract, auditConsumerConfig *auditconfv1.AuditConsumerConfig) (*kratos.App, func(), error) {
	corev1Bootstrap := runtime.Bootstrap
	corev1Registry := corev1Bootstrap.Registry
	registrar := registry.NewRegistrar(corev1Registry)
	corev1Server := corev1Bootstrap.Server
	observability := corev1Bootstrap.Obs
	app := corev1Bootstrap.App
	logger := runtime.Logger
	metricsMetrics, cleanup, err := metrics.New(observability, app, logger)
	if err != nil {
		return nil, nil, err
	}
	conn, err := data.NewClickHouseClient(clickHouse)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(conn, auditConsumerConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auditRepo := data.NewAuditRepo(dataData, logger)
	auditUsecase := biz.NewAuditUsecase(auditRepo)
	auditService := service.NewAuditService(auditUsecase)
	grpcServer := server.NewGRPCServer(corev1Server, observability, metricsMetrics, logger, auditService)
	httpServer := server.NewHTTPServer(corev1Server, observability, metricsMetrics, logger, auditService)
	client, err := newKafkaClient(kafka, auditContract, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	batchWriter := data.NewBatchWriter(dataData, auditConsumerConfig, client, logger)
	consumer := data.NewConsumer(client, batchWriter, kafka, auditContract, logger)
	kratosApp := newApp(runtime, registrar, grpcServer, httpServer, consumer)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newKafkaClient(cfg *kafkapb.Kafka, auditCfg *auditconfpb.AuditContract, l *slog.Logger) (*kgo.Client, error) {
	topic := data.DefaultTopic(auditCfg)
	group := data.DefaultConsumerGroup(cfg)
	loggerOpt := kafka.WithSlogLogger(l)
	if l != nil {
		loggerOpt = kafka.WithSlogLogger(l.With("scope", "audit/kafka"))
	}
	return kafka.NewClientOptional(context.Background(), cfg,
		loggerOpt, kgo.ConsumerGroup(group), kgo.ConsumeTopics(topic), kgo.DisableAutoCommit(),
	)
}
