// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Servora-Kit/servora/api/gen/go/servora/conf/v1"
	"github.com/Servora-Kit/servora-platform/app/audit/service/internal/biz"
	"github.com/Servora-Kit/servora-platform/app/audit/service/internal/data"
	"github.com/Servora-Kit/servora-platform/app/audit/service/internal/server"
	"github.com/Servora-Kit/servora-platform/app/audit/service/internal/service"
	"github.com/Servora-Kit/servora/pkg/bootstrap"
	"github.com/Servora-Kit/servora/pkg/broker"
	"github.com/Servora-Kit/servora/pkg/broker/kafka"
	"github.com/Servora-Kit/servora/pkg/governance/registry"
	"github.com/Servora-Kit/servora/pkg/logger"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confRegistry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	conn, err := data.NewClickHouseClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(conn, app, logger)
	if err != nil {
		return nil, nil, err
	}
	auditRepo := data.NewAuditRepo(dataData, logger)
	auditUsecase := biz.NewAuditUsecase(auditRepo)
	auditService := service.NewAuditService(auditUsecase)
	grpcServer := server.NewGRPCServer(confServer, trace, logger, auditService)
	httpServer := server.NewHTTPServer(confServer, trace, logger, auditService)
	broker := newKafkaBroker(confData, logger)
	batchWriter := data.NewBatchWriter(dataData, app, logger)
	consumer := data.NewConsumer(broker, batchWriter, confData, app, logger)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer, consumer)
	return kratosApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// newKafkaBroker wraps NewBrokerOptional with a background context for Wire injection.
func newKafkaBroker(cfg *conf.Data, l logger.Logger) broker.Broker {
	return kafka.NewBrokerOptional(context.Background(), cfg, l)
}
