// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "client_secret_hash", Type: field.TypeString, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "grant_types", Type: field.TypeJSON},
		{Name: "application_type", Type: field.TypeString, Size: 32, Default: "web"},
		{Name: "access_token_type", Type: field.TypeString, Size: 32, Default: "jwt"},
		{Name: "id_token_lifetime", Type: field.TypeInt, Default: 3600},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "applications_tenants_applications",
				Columns:    []*schema.Column{ApplicationsColumns[13]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "slug", Type: field.TypeString, Size: 128},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organizations_tenants_organizations",
				Columns:    []*schema.Column{OrganizationsColumns[7]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organization_tenant_id_slug",
				Unique:  true,
				Columns: []*schema.Column{OrganizationsColumns[7], OrganizationsColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
		},
	}
	// OrganizationMembersColumns holds the columns for the "organization_members" table.
	OrganizationMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeString, Size: 32, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "invited"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// OrganizationMembersTable holds the schema information for the "organization_members" table.
	OrganizationMembersTable = &schema.Table{
		Name:       "organization_members",
		Columns:    OrganizationMembersColumns,
		PrimaryKey: []*schema.Column{OrganizationMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_members_organizations_members",
				Columns:    []*schema.Column{OrganizationMembersColumns[5]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_members_users_org_memberships",
				Columns:    []*schema.Column{OrganizationMembersColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationmember_organization_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationMembersColumns[5], OrganizationMembersColumns[6]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"business", "personal"}, Default: "business"},
		{Name: "domain", Type: field.TypeString, Unique: true, Nullable: true, Size: 128},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// TenantMembersColumns holds the columns for the "tenant_members" table.
	TenantMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "admin", "member"}, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "invited"}, Default: "active"},
		{Name: "joined_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// TenantMembersTable holds the schema information for the "tenant_members" table.
	TenantMembersTable = &schema.Table{
		Name:       "tenant_members",
		Columns:    TenantMembersColumns,
		PrimaryKey: []*schema.Column{TenantMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenant_members_tenants_members",
				Columns:    []*schema.Column{TenantMembersColumns[6]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tenant_members_users_tenant_members",
				Columns:    []*schema.Column{TenantMembersColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tenantmember_tenant_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{TenantMembersColumns[6], TenantMembersColumns[7]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 32, Default: "user"},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		OrganizationsTable,
		OrganizationMembersTable,
		TenantsTable,
		TenantMembersTable,
		UsersTable,
	}
)

func init() {
	ApplicationsTable.ForeignKeys[0].RefTable = TenantsTable
	ApplicationsTable.Annotation = &entsql.Annotation{
		Table: "applications",
	}
	OrganizationsTable.ForeignKeys[0].RefTable = TenantsTable
	OrganizationsTable.Annotation = &entsql.Annotation{
		Table: "organizations",
	}
	OrganizationMembersTable.ForeignKeys[0].RefTable = OrganizationsTable
	OrganizationMembersTable.ForeignKeys[1].RefTable = UsersTable
	OrganizationMembersTable.Annotation = &entsql.Annotation{
		Table: "organization_members",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
	TenantMembersTable.ForeignKeys[0].RefTable = TenantsTable
	TenantMembersTable.ForeignKeys[1].RefTable = UsersTable
	TenantMembersTable.Annotation = &entsql.Annotation{
		Table: "tenant_members",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
