// Package authz provides a generic Kratos middleware for OpenFGA-based authorization.
// It is driven by per-operation AuthzRule maps, typically generated by protoc-gen-servora-authz.
//
// Example usage in a service:
//
//	import pkgauthz "github.com/Servora-Kit/servora/pkg/authz"
//	import orderpb "github.com/Servora-Kit/servora/api/gen/go/servora/order/service/v1"
//
//	mw = append(mw, pkgauthz.Authz(
//	    pkgauthz.WithFGAClient(fgaClient),
//	    pkgauthz.WithAuthzRules(orderpb.AuthzRules),
//	    pkgauthz.WithAuthzCache(redisClient, 60*time.Second),
//	))
package authz

import (
	"context"
	"fmt"
	"time"

	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/middleware"
	"github.com/go-kratos/kratos/v2/transport"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	authzpb "github.com/Servora-Kit/servora/api/gen/go/servora/authz/service/v1"
	"github.com/Servora-Kit/servora/pkg/actor"
	"github.com/Servora-Kit/servora/pkg/audit"
	"github.com/Servora-Kit/servora/pkg/openfga"
	"github.com/Servora-Kit/servora/pkg/redis"
)

// AuthzRule describes the authorization requirement for a single RPC operation.
type AuthzRule struct {
	Mode       authzpb.AuthzMode
	Relation   string
	ObjectType string
	// IDField is the proto field name to extract object ID from the request.
	// When empty, "default" is used as the object ID (singleton/platform-level checks).
	IDField string
}

// Option configures the Authz middleware.
type Option func(*authzConfig)

type authzConfig struct {
	fga      *openfga.Client
	redis    *redis.Client
	cacheTTL time.Duration
	rules    map[string]AuthzRule
	recorder *audit.Recorder
}

// WithFGAClient sets the OpenFGA client used for authorization checks.
func WithFGAClient(c *openfga.Client) Option {
	return func(cfg *authzConfig) { cfg.fga = c }
}

// WithAuthzRules sets the operation→rule mapping.
func WithAuthzRules(rules map[string]AuthzRule) Option {
	return func(cfg *authzConfig) { cfg.rules = rules }
}

// WithAuthzCache enables Redis caching of authorization check results.
func WithAuthzCache(rdb *redis.Client, ttl time.Duration) Option {
	return func(cfg *authzConfig) {
		cfg.redis = rdb
		cfg.cacheTTL = ttl
	}
}

// WithAuditRecorder injects an audit recorder that emits authz.decision events
// after each authorization check. Passing nil disables audit emission.
func WithAuditRecorder(r *audit.Recorder) Option {
	return func(cfg *authzConfig) { cfg.recorder = r }
}

// Authz returns a Kratos middleware that performs OpenFGA authorization checks.
//
// Behavior:
//   - No transport in context → passthrough (non-server calls)
//   - No rule for operation → fail-closed (403 AUTHZ_NO_RULE)
//   - AUTHZ_MODE_NONE → skip (public endpoint)
//   - AUTHZ_MODE_CHECK, no actor or anonymous → 403 AUTHZ_DENIED
//   - AUTHZ_MODE_CHECK, nil FGA client → 503 AUTHZ_UNAVAILABLE
//   - AUTHZ_MODE_CHECK, allowed → handler called
//   - AUTHZ_MODE_CHECK, denied → 403 AUTHZ_DENIED
func Authz(opts ...Option) middleware.Middleware {
	cfg := &authzConfig{}
	for _, o := range opts {
		o(cfg)
	}

	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req any) (any, error) {
			tr, ok := transport.FromServerContext(ctx)
			if !ok {
				return handler(ctx, req)
			}

			operation := tr.Operation()
			rule, found := cfg.rules[operation]
			if !found {
				return nil, errors.Forbidden("AUTHZ_NO_RULE",
					fmt.Sprintf("no authorization rule for operation %s", operation))
			}

			if rule.Mode == authzpb.AuthzMode_AUTHZ_MODE_NONE {
				return handler(ctx, req)
			}

			a, ok := actor.FromContext(ctx)
			if !ok || a.Type() != actor.TypeUser {
				return nil, errors.Forbidden("AUTHZ_DENIED", "authentication required")
			}
			userID := a.ID()

			if cfg.fga == nil {
				return nil, errors.ServiceUnavailable("AUTHZ_UNAVAILABLE", "authorization service not available")
			}

			objectType, objectID, err := resolveObject(rule, req)
			if err != nil {
				return nil, errors.BadRequest("AUTHZ_BAD_REQUEST",
					fmt.Sprintf("cannot resolve authorization target: %v", err))
			}

			relation := rule.Relation
			ttl := cfg.cacheTTL
			if ttl == 0 {
				ttl = openfga.DefaultCheckCacheTTL
			}
			principal := "user:" + userID
			allowed, cacheHit, err := cfg.fga.CachedCheck(ctx, cfg.redis, ttl,
				principal, relation, objectType, objectID)
			if err != nil {
				cfg.emitAuthzDecision(ctx, operation, a, audit.AuthzDetail{
					Relation:    relation,
					ObjectType:  objectType,
					ObjectID:    objectID,
					Decision:    audit.AuthzDecisionError,
					CacheHit:    cacheHit,
					ErrorReason: err.Error(),
				})
				return nil, errors.ServiceUnavailable("AUTHZ_CHECK_FAILED",
					fmt.Sprintf("authorization check failed: %v", err))
			}
			if !allowed {
				cfg.emitAuthzDecision(ctx, operation, a, audit.AuthzDetail{
					Relation:   relation,
					ObjectType: objectType,
					ObjectID:   objectID,
					Decision:   audit.AuthzDecisionDenied,
					CacheHit:   cacheHit,
				})
				return nil, errors.Forbidden("AUTHZ_DENIED", "insufficient permissions")
			}

			cfg.emitAuthzDecision(ctx, operation, a, audit.AuthzDetail{
				Relation:   relation,
				ObjectType: objectType,
				ObjectID:   objectID,
				Decision:   audit.AuthzDecisionAllowed,
				CacheHit:   cacheHit,
			})
			return handler(ctx, req)
		}
	}
}

func (cfg *authzConfig) emitAuthzDecision(ctx context.Context, operation string, a actor.Actor, detail audit.AuthzDetail) {
	if cfg.recorder == nil {
		return
	}
	cfg.recorder.RecordAuthzDecision(ctx, operation, a, detail)
}

// resolveObject determines the FGA object type and ID for the given rule and request.
// For AUTHZ_MODE_CHECK:
//   - ObjectType is taken directly from rule.ObjectType (e.g. "platform")
//   - ObjectID is extracted from the proto request field named by rule.IDField,
//     or defaults to "default" when IDField is empty (e.g. platform-level checks).
func resolveObject(rule AuthzRule, req any) (objectType, objectID string, err error) {
	objectType = rule.ObjectType
	if objectType == "" {
		return "", "", fmt.Errorf("object_type not specified in authz rule")
	}

	if rule.IDField == "" {
		return objectType, "default", nil
	}

	objectID, err = extractProtoField(req, rule.IDField)
	return
}

func extractProtoField(req any, fieldName string) (string, error) {
	if fieldName == "" {
		return "", fmt.Errorf("id_field not specified")
	}

	msg, ok := req.(proto.Message)
	if !ok {
		return "", fmt.Errorf("request is not a proto message")
	}

	md := msg.ProtoReflect().Descriptor()
	fd := md.Fields().ByName(protoreflect.Name(fieldName))
	if fd == nil {
		return "", fmt.Errorf("field %q not found in %s", fieldName, md.FullName())
	}

	val := msg.ProtoReflect().Get(fd)
	s := val.String()
	if s == "" {
		return "", fmt.Errorf("field %q is empty", fieldName)
	}
	return s, nil
}
