// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/plateau/api/gen/go/iam/conf/v1"
	"github.com/Servora-Kit/plateau/api/gen/go/iam/oidc/conf/v1"
	"github.com/Servora-Kit/plateau/api/gen/go/plateau/infra/mail/v1"
	"github.com/Servora-Kit/plateau/api/gen/go/plateau/infra/openfga/v1"
	"github.com/Servora-Kit/plateau/api/gen/go/plateau/security/cap/v1"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/authn"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/authz"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/biz"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/data"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/mail"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/oidc"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/server"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/service"
	"github.com/Servora-Kit/plateau/app/iam/service/internal/startup"
	cap2 "github.com/Servora-Kit/plateau/security/cap"
	"github.com/Servora-Kit/servora/api/gen/go/servora/contrib/db/redis/v1"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/Servora-Kit/servora/obs/metrics"
	"github.com/go-kratos/kratos/v3"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(runtime *bootstrap.Runtime, iam *iamconfv1.IAM, oidcconfv1OIDC *oidcconfv1.OIDC, capv1CAP *capv1.CAP, redis *redispb.Redis, mailpbMail *mailpb.Mail, openFGA *openfgaconfpb.OpenFGA) (*kratos.App, func(), error) {
	corev1Bootstrap := runtime.Bootstrap
	corev1Registry := corev1Bootstrap.Registry
	registrar := registry.NewRegistrar(corev1Registry)
	corev1Server := corev1Bootstrap.Server
	observability := corev1Bootstrap.Obs
	app := corev1Bootstrap.App
	logger := runtime.Logger
	metricsMetrics, cleanup, err := metrics.New(observability, app, logger)
	if err != nil {
		return nil, nil, err
	}
	corev1Data := corev1Bootstrap.Data
	driver, err := data.NewEntDriver(corev1Data)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := data.NewDBClient(driver)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := data.NewRedisClient(redis)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	openFgaClient, err := data.NewFGAClient(openFGA)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataData, err := data.NewData(client, redisClient, openFgaClient, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepo, err := data.NewUserRepository(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sessionRepo, err := data.NewSessionRepository(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	tokenSessionRepo, err := data.NewTokenSessionRepository(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sessionUsecase, err := biz.NewSessionUsecase(userRepo, sessionRepo, tokenSessionRepo)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v, err := authn.NewSessionAuthenticator(sessionUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authorizer, err := authz.NewOpenFGAAuthorizer(openFgaClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	credentialRepo, err := data.NewCredentialRepository(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authenticationUsecase, err := biz.NewAuthenticationUsecase(userRepo, credentialRepo, sessionUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authnService, err := service.NewAuthnService(authenticationUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sessionService, err := service.NewSessionService(sessionUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	verificationTokenRepo, err := data.NewVerificationTokenRepo(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	passwordResetTokenRepo, err := data.NewPasswordResetTokenRepository(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	capCap, err := cap2.New(capv1CAP, redisClient)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	capVerifier := data.NewCAPVerifier(capCap)
	sender, err := mail.NewSender(mailpbMail)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	from, err := mail.NewFrom(mailpbMail)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	templates, err := mail.NewTemplates()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mailer, err := mail.NewMailer(sender, from, templates)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mailSender := mail.NewMailSender(mailer)
	accountUsecase, err := biz.NewAccountUsecase(userRepo, credentialRepo, verificationTokenRepo, passwordResetTokenRepo, capVerifier, mailSender, sessionUsecase, runtime)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	accountService, err := service.NewAccountService(accountUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userUsecase, err := biz.NewUserUsecase(accountUsecase, userRepo, sessionUsecase, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService, err := service.NewUserService(userUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(corev1Server, observability, metricsMetrics, v, authorizer, authnService, sessionService, accountService, userService, logger)
	oidcStorage, err := oidc.NewOIDCStorage(client, oidcconfv1OIDC)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iamProvider, err := oidc.NewIAMProvider(oidcconfv1OIDC, oidcStorage, sessionUsecase)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(corev1Server, observability, metricsMetrics, capCap, iamProvider, v, authorizer, authnService, sessionService, accountService, userService, logger)
	initialAdminCreator, err := data.NewInitialAdminCreator(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminRelationWriter, err := data.NewAdminRelationWriter(dataData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	adminInitializer, err := biz.NewAdminInitializer(iam, userRepo, initialAdminCreator, adminRelationWriter, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	oidcInitializer, err := oidc.NewOIDCInitializer(oidcconfv1OIDC, oidcStorage)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	initializer, err := startup.NewInitializer(adminInitializer, oidcInitializer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(runtime, registrar, grpcServer, httpServer, initializer, dataData)
	return kratosApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
