// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora/api/gen/go/servora/conf/v1"
	conf2 "github.com/Servora-Kit/servora/api/gen/go/servora/iam/conf/v1"
	"github.com/Servora-Kit/servora/app/iam/service/internal/biz"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data"
	"github.com/Servora-Kit/servora/app/iam/service/internal/oidc"
	"github.com/Servora-Kit/servora/app/iam/service/internal/server"
	"github.com/Servora-Kit/servora/app/iam/service/internal/service"
	"github.com/Servora-Kit/servora/pkg/bootstrap"
	cap2 "github.com/Servora-Kit/servora/pkg/cap"
	"github.com/Servora-Kit/servora/pkg/governance/registry"
	"github.com/Servora-Kit/servora/pkg/governance/telemetry"
	"github.com/Servora-Kit/servora/pkg/jwks"
	"github.com/Servora-Kit/servora/pkg/openfga"
	"github.com/Servora-Kit/servora/pkg/transport/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discovery *conf.Discovery, confRegistry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, mail *conf.Mail, confBiz *conf2.Biz, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	keyManager, err := jwks.NewKeyManagerFromConfig(app)
	if err != nil {
		return nil, nil, err
	}
	openfgaClient := openfga.NewClientOptional(app, logger)
	redisClient, cleanup, err := data.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	grpcMiddleware := server.NewGRPCMiddleware(trace, telemetryMetrics, logger, keyManager, openfgaClient, redisClient)
	driver, err := data.NewEntDriver(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	entClient, err := data.NewDBClient(driver, app, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registryDiscovery := registry.NewDiscovery(discovery)
	clientClient, err := client.NewClient(confData, trace, registryDiscovery, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(entClient, confData, logger, clientClient, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authnRepo := data.NewAuthnRepo(dataData, logger)
	otpRepo := data.NewOTPRepo(redisClient, logger)
	sender := data.NewMailSender(mail)
	authnUsecase := biz.NewAuthnUsecase(authnRepo, otpRepo, sender, mail, logger, app, keyManager)
	capCap := cap2.New(redisClient)
	authnService := service.NewAuthnService(authnUsecase, capCap)
	userRepo := data.NewUserRepo(dataData, logger)
	authZRepo := data.NewAuthZRepo(openfgaClient, redisClient)
	userUsecase := biz.NewUserUsecase(userRepo, logger, app, authnRepo, authnUsecase, authZRepo)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, grpcMiddleware, logger, authnService, userService)
	httpMiddleware := server.NewHTTPMiddleware(trace, telemetryMetrics, logger, keyManager, openfgaClient, redisClient)
	handler := server.NewHealthHandler(redisClient, driver)
	applicationRepo := data.NewApplicationRepo(dataData, logger)
	applicationUsecase := biz.NewApplicationUsecase(applicationRepo, logger)
	applicationService := service.NewApplicationService(applicationUsecase)
	storage := data.NewOIDCStorage(dataData, keyManager, authnRepo, redisClient, app, logger)
	provider, err := oidc.NewProvider(app, storage)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	loginHandler := oidc.NewLoginHandler(app, redisClient, logger)
	loginCompleteHandler := oidc.NewLoginCompleteHandler(loginHandler, keyManager, authnRepo)
	httpServer := server.NewHTTPServer(confServer, app, httpMiddleware, telemetryMetrics, logger, handler, authnService, userService, applicationService, capCap, provider, loginHandler, loginCompleteHandler)
	seeder := data.NewSeeder(entClient, openfgaClient, confBiz, logger)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer, seeder)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
