// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora/api/gen/go/conf/v1"
	"github.com/Servora-Kit/servora/app/iam/service/internal/biz"
	"github.com/Servora-Kit/servora/app/iam/service/internal/data"
	"github.com/Servora-Kit/servora/app/iam/service/internal/server"
	"github.com/Servora-Kit/servora/app/iam/service/internal/service"
	"github.com/Servora-Kit/servora/pkg/bootstrap"
	"github.com/Servora-Kit/servora/pkg/governance/registry"
	"github.com/Servora-Kit/servora/pkg/governance/telemetry"
	"github.com/Servora-Kit/servora/pkg/jwks"
	"github.com/Servora-Kit/servora/pkg/openfga"
	"github.com/Servora-Kit/servora/pkg/transport/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discovery *conf.Discovery, confRegistry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	grpcMiddleware := server.NewGRPCMiddleware(trace, telemetryMetrics, logger)
	entClient, err := data.NewDBClient(confData, app, logger)
	if err != nil {
		return nil, nil, err
	}
	registryDiscovery := registry.NewDiscovery(discovery)
	clientClient, err := client.NewClient(confData, trace, registryDiscovery, logger)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup, err := data.NewRedis(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(entClient, confData, logger, clientClient, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	keyManager, err := jwks.NewKeyManagerFromConfig(app)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	organizationRepo := data.NewOrganizationRepo(dataData, logger)
	projectRepo := data.NewProjectRepo(dataData, logger)
	openfgaClient := openfga.NewClientOptional(app, logger)
	platformRootID, err := data.NewPlatformRootID(entClient, openfgaClient, app, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	organizationUsecase := biz.NewOrganizationUsecase(organizationRepo, projectRepo, openfgaClient, logger, platformRootID)
	projectUsecase := biz.NewProjectUsecase(projectRepo, organizationRepo, openfgaClient, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, logger, app, keyManager, organizationUsecase, projectUsecase)
	authService := service.NewAuthService(authUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, app, authRepo, organizationRepo, projectRepo, openfgaClient, platformRootID)
	userService := service.NewUserService(userUsecase)
	testRepo := data.NewTestRepo(dataData, logger)
	testUsecase := biz.NewTestUsecase(testRepo, logger)
	testService := service.NewTestService(testUsecase)
	organizationService := service.NewOrganizationService(organizationUsecase)
	projectService := service.NewProjectService(projectUsecase)
	grpcServer := server.NewGRPCServer(confServer, grpcMiddleware, logger, authService, userService, testService, organizationService, projectService)
	httpMiddleware := server.NewHTTPMiddleware(trace, telemetryMetrics, logger, keyManager, openfgaClient, platformRootID)
	handler := server.NewHealthHandler(redisClient)
	httpServer := server.NewHTTPServer(confServer, app, httpMiddleware, telemetryMetrics, logger, handler, keyManager, authService, userService, testService, organizationService, projectService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
