apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: servora
spec:
  selector:
    app: SERVICE_NAME
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: grpc
    port: 9000
    targetPort: grpc
  type: ClusterIP
