package audit

import (
	"context"

	"github.com/go-kratos/kratos/v2/middleware"
	"github.com/go-kratos/kratos/v2/transport"

	"github.com/Servora-Kit/servora/pkg/actor"
)

// Rule describes how a specific RPC operation should be audited.
type Rule struct {
	// EventType is the audit event type to emit.
	EventType EventType
	// Operation override (defaults to the gRPC operation path).
	Operation string
	// TargetType is the resource type being operated on (e.g. "user").
	TargetType string
	// MutationType specifies the mutation kind (create/update/delete) for
	// EventTypeResourceMutation rules. Defaults to ResourceMutationUpdate if unset.
	MutationType ResourceMutationType
	// RecordOnError controls whether to emit events even when the handler fails.
	RecordOnError bool
	// TargetIDFunc extracts the target resource ID from the request/response.
	// Generated by protoc-gen-servora-audit for rules with target_id_field set.
	// Called after handler returns; req is the original request, resp is the handler response.
	TargetIDFunc func(req, resp any) string
}

// AuditMiddlewareOption configures the audit middleware.
type AuditMiddlewareOption func(*auditMiddlewareConfig)

type auditMiddlewareConfig struct {
	rules    map[string]Rule // keyed by gRPC operation path
	recorder *Recorder
}

// WithRules sets the per-operation audit rules directly.
func WithRules(rules map[string]Rule) AuditMiddlewareOption {
	return func(c *auditMiddlewareConfig) { c.rules = rules }
}

// WithRulesFunc sets the per-operation audit rules via a function (e.g. generated AuditRules()).
// The function is called once during middleware construction.
func WithRulesFunc(fn func() map[string]Rule) AuditMiddlewareOption {
	return func(c *auditMiddlewareConfig) {
		if fn != nil {
			c.rules = fn()
		}
	}
}

// WithRecorder sets the Recorder to use for emitting events.
func WithRecorder(r *Recorder) AuditMiddlewareOption {
	return func(c *auditMiddlewareConfig) { c.recorder = r }
}

// Audit returns a Kratos middleware that records audit events based on configured rules.
// Operations with no matching rule are passed through silently.
//
// This is a skeleton — full implementation follows in phase 2 when audit middleware
// is integrated with real service handlers.
func Audit(opts ...AuditMiddlewareOption) middleware.Middleware {
	cfg := &auditMiddlewareConfig{}
	for _, opt := range opts {
		opt(cfg)
	}
	if cfg.recorder == nil {
		cfg.recorder = NewRecorder(NewNoopEmitter(), "")
	}

	return func(handler middleware.Handler) middleware.Handler {
		return func(ctx context.Context, req any) (any, error) {
			tr, ok := transport.FromServerContext(ctx)
			if !ok {
				return handler(ctx, req)
			}

			operation := tr.Operation()
			rule, hasRule := cfg.rules[operation]
			if !hasRule {
				return handler(ctx, req)
			}

			// Execute the handler.
			resp, err := handler(ctx, req)

			// Determine whether to emit.
			if err != nil && !rule.RecordOnError {
				return resp, err
			}

			a, _ := actor.FromContext(ctx)
			opName := rule.Operation
			if opName == "" {
				opName = operation
			}

			targetInfo := TargetInfo{Type: rule.TargetType}
			if rule.TargetIDFunc != nil {
				targetInfo.ID = rule.TargetIDFunc(req, resp)
			}

			switch rule.EventType {
			case EventTypeResourceMutation:
				mutType := rule.MutationType
				if mutType == "" {
					mutType = ResourceMutationUpdate
				}
				detail := ResourceMutationDetail{
					MutationType: mutType,
					ResourceType: rule.TargetType,
					ResourceID:   targetInfo.ID,
				}
				cfg.recorder.RecordResourceMutation(ctx, opName, a, targetInfo, detail, err)
			}

			return resp, err
		}
	}
}
