receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog/audit:
    include:
      - /var/log/audit/audit.service.log
    start_at: end
    include_file_path: true
    operators:
      - type: json_parser
    resource:
      service.name: audit.service

processors:
  batch:
  attributes/log_hints:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: service.name,level,module,operation

exporters:
  otlp_grpc/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp_http/loki:
    endpoint: http://loki:3100/otlp

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  telemetry:
    metrics:
      level: basic
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/jaeger]
    logs:
      receivers: [filelog/audit]
      processors: [attributes/log_hints, batch]
      exporters: [otlp_http/loki]
