// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Application is the predicate function for application builders.
type Application func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationMember is the predicate function for organizationmember builders.
type OrganizationMember func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantMember is the predicate function for tenantmember builders.
type TenantMember func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
