package main

import (
	"fmt"
	"path"
	"sort"

	authzpb "github.com/Servora-Kit/servora/api/gen/go/servora/authz/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		// ruleParams holds the authorization parameters extracted from a proto annotation.
		type ruleParams struct {
			Mode       authzpb.AuthzMode
			Relation   string
			ObjectType string
			IDField    string
		}

		// Build a rule-template index: shortServiceName → methodName → params.
		//
		// Scanning ALL files (including non-generated dependencies) makes authz
		// annotations on pure-RPC protos (e.g. user.proto) visible when the plugin
		// processes their HTTP-gateway counterparts (e.g. i_user.proto), which import
		// the pure-RPC protos as dependencies.  This allows annotations to live on the
		// canonical gRPC definition rather than being duplicated on the gateway file.
		templates := map[string]map[string]ruleParams{}
		for _, f := range gen.Files {
			for _, svc := range f.Services {
				shortName := string(svc.Desc.Name())
				for _, m := range svc.Methods {
					ext := proto.GetExtension(m.Desc.Options(), authzpb.E_Rule)
					r, ok := ext.(*authzpb.AuthzRule)
					if !ok || r == nil || r.Mode == authzpb.AuthzMode_AUTHZ_MODE_UNSPECIFIED {
						continue
					}
					if templates[shortName] == nil {
						templates[shortName] = map[string]ruleParams{}
					}
					templates[shortName][string(m.Desc.Name())] = ruleParams{
						Mode:       r.Mode,
						Relation:   r.Relation,
						ObjectType: r.ObjectType,
						IDField:    r.IdField,
					}
				}
			}
		}

		if len(templates) == 0 {
			return nil
		}

		// Group generated files by output directory.
		// Each directory receives exactly one authz_rules.gen.go that covers every
		// service defined in that directory, resolved via the template index above.
		//
		// Example outcome for the IAM module:
		//   user/service/v1/authz_rules.gen.go       — user.service.v1.UserService rules
		//   authn/service/v1/authz_rules.gen.go       — authn.service.v1.AuthnService rules
		//   application/service/v1/authz_rules.gen.go — application.service.v1.ApplicationService rules
		//   iam/service/v1/authz_rules.gen.go         — iam.service.v1.{User,Authn,Application}Service rules
		type dirGroup struct {
			targetFile *protogen.File
			seen       map[string]bool // deduplicate by operation key
			rules      []ruleEntry
		}
		groups := map[string]*dirGroup{}

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			dir := path.Dir(f.GeneratedFilenamePrefix)
			for _, svc := range f.Services {
				methods, ok := templates[string(svc.Desc.Name())]
				if !ok {
					continue
				}
				if groups[dir] == nil {
					groups[dir] = &dirGroup{
						targetFile: f,
						seen:       map[string]bool{},
					}
				}
				fullName := string(svc.Desc.FullName())
				for methodName, p := range methods {
					op := fmt.Sprintf("/%s/%s", fullName, methodName)
					if groups[dir].seen[op] {
						continue
					}
					groups[dir].seen[op] = true
					groups[dir].rules = append(groups[dir].rules, ruleEntry{
						Operation:  op,
						Mode:       p.Mode,
						Relation:   p.Relation,
						ObjectType: p.ObjectType,
						IDField:    p.IDField,
					})
				}
			}
		}

		for dir, group := range groups {
			sort.Slice(group.rules, func(i, j int) bool {
				return group.rules[i].Operation < group.rules[j].Operation
			})
			g := gen.NewGeneratedFile(
				path.Join(dir, "authz_rules.gen.go"),
				group.targetFile.GoImportPath,
			)
			generateFile(g, group.targetFile.GoPackageName, group.rules)
		}

		return nil
	})
}

type ruleEntry struct {
	Operation  string
	Mode       authzpb.AuthzMode
	Relation   string
	ObjectType string
	IDField    string
}

func generateFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, rules []ruleEntry) {
	authzPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/api/gen/go/servora/authz/v1")
	pkgAuthzPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/pkg/authz")

	g.P("// Code generated by protoc-gen-servora-authz. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	authzRule := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuthzRule", GoImportPath: pkgAuthzPkg})

	g.P("// _authzRules is the immutable backing store for AuthzRules.")
	g.P("var _authzRules = map[string]", authzRule, "{")
	for _, r := range rules {
		modeIdent := g.QualifiedGoIdent(protogen.GoIdent{
			GoName:       "AuthzMode_" + r.Mode.String(),
			GoImportPath: authzPkg,
		})
		g.P(fmt.Sprintf("	%q: {", r.Operation))
		g.P("		Mode: ", modeIdent, ",")
		if r.Relation != "" {
			g.P(fmt.Sprintf("		Relation: %q,", r.Relation))
		}
		if r.ObjectType != "" {
			g.P(fmt.Sprintf("		ObjectType: %q,", r.ObjectType))
		}
		if r.IDField != "" {
			g.P(fmt.Sprintf("		IDField: %q,", r.IDField))
		}
		g.P("	},")
	}
	g.P("}")
	g.P()
	g.P("// AuthzRules returns a copy of the authorization rules for this package.")
	g.P("// Each call returns an independent map; callers may not modify the returned map.")
	g.P("func AuthzRules() map[string]", authzRule, " {")
	g.P("	m := make(map[string]", authzRule, ", len(_authzRules))")
	g.P("	for k, v := range _authzRules {")
	g.P("		m[k] = v")
	g.P("	}")
	g.P("	return m")
	g.P("}")
}
