package main

import (
	"fmt"
	"path"
	"sort"

	authzpb "github.com/Servora-Kit/servora/api/gen/go/servora/authz/service/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		// Build an index of serviceName → []fullServiceName across ALL proto
		// files (including non-generated dependencies). This lets us discover
		// that e.g. "UserService" exists in both iam.service.v1 and
		// user.service.v1, so we can emit rules for both operation namespaces.
		svcAliases := map[string][]string{}
		for _, f := range gen.Files {
			for _, svc := range f.Services {
				name := string(svc.Desc.Name())
				full := string(svc.Desc.FullName())
				svcAliases[name] = append(svcAliases[name], full)
			}
		}

		var rules []ruleEntry
		var targetFile *protogen.File

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, svc := range f.Services {
				for _, m := range svc.Methods {
					ext := proto.GetExtension(m.Desc.Options(), authzpb.E_Rule)
					if ext == nil {
						continue
					}
					r, ok := ext.(*authzpb.AuthzRule)
					if !ok || r == nil || r.Mode == authzpb.AuthzMode_AUTHZ_MODE_UNSPECIFIED {
						continue
					}
					if targetFile == nil {
						targetFile = f
					}
					methodName := string(m.Desc.Name())
					svcName := string(svc.Desc.Name())

					for _, fullSvc := range svcAliases[svcName] {
						rules = append(rules, ruleEntry{
							Operation:  fmt.Sprintf("/%s/%s", fullSvc, methodName),
							Mode:       r.Mode,
							Relation:   r.Relation,
							ObjectType: r.ObjectType,
							IDField:    r.IdField,
						})
					}
				}
			}
		}

		if len(rules) == 0 || targetFile == nil {
			return nil
		}

		sort.Slice(rules, func(i, j int) bool {
			return rules[i].Operation < rules[j].Operation
		})

		dir := path.Dir(targetFile.GeneratedFilenamePrefix)
		g := gen.NewGeneratedFile(path.Join(dir, "authz_rules.gen.go"), targetFile.GoImportPath)
		generateFile(g, targetFile.GoPackageName, rules)
		return nil
	})
}

type ruleEntry struct {
	Operation  string
	Mode       authzpb.AuthzMode
	Relation   string
	ObjectType string
	IDField    string
}

func generateFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, rules []ruleEntry) {
	authzPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/api/gen/go/servora/authz/service/v1")
	pkgAuthzPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/pkg/authz")

	g.P("// Code generated by protoc-gen-servora-authz. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	authzRule := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuthzRule", GoImportPath: pkgAuthzPkg})

	g.P("// AuthzRules maps each annotated RPC operation to its authorization rule.")
	g.P("var AuthzRules = map[string]", authzRule, "{")
	for _, r := range rules {
		modeIdent := g.QualifiedGoIdent(protogen.GoIdent{
			GoName:       "AuthzMode_" + r.Mode.String(),
			GoImportPath: authzPkg,
		})
		g.P(fmt.Sprintf("	%q: {", r.Operation))
		g.P("		Mode: ", modeIdent, ",")
		if r.Relation != "" {
			g.P(fmt.Sprintf("		Relation: %q,", r.Relation))
		}
		if r.ObjectType != "" {
			g.P(fmt.Sprintf("		ObjectType: %q,", r.ObjectType))
		}
		if r.IDField != "" {
			g.P(fmt.Sprintf("		IDField: %q,", r.IDField))
		}
		g.P("	},")
	}
	g.P("}")
}
