package main

import (
	"fmt"
	"path"
	"strings"

	mapperpb "github.com/Servora-Kit/servora/api/gen/go/servora/mapper/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			if err := processFile(gen, f); err != nil {
				return err
			}
		}
		return nil
	})
}

type messageEntry struct {
	GoName          string
	Presets         []string
	FieldMap        map[string]string // entity field -> proto field rename
	FieldConverters map[string]string // proto field name -> ConverterKind constant name
	IgnoredFields   []string
	CustomHooks     []string
}

func processFile(gen *protogen.Plugin, f *protogen.File) error {
	var entries []messageEntry

	for _, msg := range f.Messages {
		ext := proto.GetExtension(msg.Desc.Options(), mapperpb.E_Mapper)
		if ext == nil {
			continue
		}
		rule, ok := ext.(*mapperpb.MapperMessageRule)
		if !ok || rule == nil || !rule.Enabled {
			continue
		}

		entry := messageEntry{
			GoName:          msg.GoIdent.GoName,
			Presets:         rule.Presets,
			FieldMap:        make(map[string]string),
			FieldConverters: make(map[string]string),
		}

		for _, field := range msg.Fields {
			fext := proto.GetExtension(field.Desc.Options(), mapperpb.E_MapperField)
			if fext == nil {
				continue
			}
			fr, ok := fext.(*mapperpb.MapperFieldRule)
			if !ok || fr == nil {
				continue
			}
			if fr.Ignore {
				entry.IgnoredFields = append(entry.IgnoredFields, field.GoName)
				continue
			}
			if fr.Rename != "" {
				entry.FieldMap[fr.Rename] = field.GoName
			}
			if fr.Converter != mapperpb.ConverterKind_CONVERTER_KIND_UNSPECIFIED {
				entry.FieldConverters[field.GoName] = converterKindToConstant(fr.Converter)
			}
			if fr.Custom != "" {
				entry.CustomHooks = append(entry.CustomHooks, fr.Custom)
			}
		}

		entries = append(entries, entry)
	}

	if len(entries) == 0 {
		return nil
	}

	dir := path.Dir(f.GeneratedFilenamePrefix)
	baseName := path.Base(f.GeneratedFilenamePrefix)
	outFile := path.Join(dir, baseName+"_mapper.gen.go")
	g := gen.NewGeneratedFile(outFile, f.GoImportPath)
	generateMapperFile(g, f.GoPackageName, entries)
	return nil
}

func generateMapperFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, entries []messageEntry) {
	mapperPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/pkg/mapper")

	g.P("// Code generated by protoc-gen-servora-mapper. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	mapperPlan := g.QualifiedGoIdent(protogen.GoIdent{GoName: "MapperPlan", GoImportPath: mapperPkg})

	for _, e := range entries {
		g.P("// ", e.GoName, "MapperPlan returns the declarative mapper plan")
		g.P("// extracted from proto annotations on the ", e.GoName, " message.")
		g.P("func ", e.GoName, "MapperPlan() *", mapperPlan, " {")
		g.P("	return &", mapperPlan, "{")

		if len(e.Presets) > 0 {
			g.P("		Presets: []string{", formatStringSlice(e.Presets), "},")
		}

		if len(e.FieldMap) > 0 {
			g.P("		FieldMapping: map[string]string{")
			for k, v := range e.FieldMap {
				g.P(fmt.Sprintf("			%q: %q,", k, v))
			}
			g.P("		},")
		}

		if len(e.FieldConverters) > 0 {
			converterKind := g.QualifiedGoIdent(protogen.GoIdent{GoName: "ConverterKind", GoImportPath: mapperPkg})
			g.P("		FieldConverters: map[string]", converterKind, "{")
			for field, kind := range e.FieldConverters {
				kindIdent := g.QualifiedGoIdent(protogen.GoIdent{GoName: kind, GoImportPath: mapperPkg})
				g.P(fmt.Sprintf("			%q: ", field), kindIdent, ",")
			}
			g.P("		},")
		}

		if len(e.IgnoredFields) > 0 {
			g.P("		IgnoredFields: []string{", formatStringSlice(e.IgnoredFields), "},")
		}

		if len(e.CustomHooks) > 0 {
			g.P("		CustomHooks: []string{", formatStringSlice(e.CustomHooks), "},")
		}

		g.P("	}")
		g.P("}")
		g.P()
	}
}

func converterKindToConstant(kind mapperpb.ConverterKind) string {
	switch kind {
	case mapperpb.ConverterKind_CONVERTER_KIND_TIMESTAMP_TIME:
		return "ConverterTimestampTime"
	case mapperpb.ConverterKind_CONVERTER_KIND_TIME_PTR:
		return "ConverterTimePTR"
	case mapperpb.ConverterKind_CONVERTER_KIND_STRING_PTR:
		return "ConverterStringPTR"
	case mapperpb.ConverterKind_CONVERTER_KIND_INT64_PTR:
		return "ConverterInt64PTR"
	case mapperpb.ConverterKind_CONVERTER_KIND_ENUM_STRING:
		return "ConverterEnumString"
	case mapperpb.ConverterKind_CONVERTER_KIND_UUID_STRING:
		return "ConverterUUIDString"
	case mapperpb.ConverterKind_CONVERTER_KIND_INT_INT32:
		return "ConverterIntInt32"
	default:
		return ""
	}
}

func formatStringSlice(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}
