/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as PlatformTenantsIndexRouteImport } from './routes/_platform/tenants/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app/applications/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppApplicationsAppIdRouteImport } from './routes/_app/applications/$appId'
import { Route as PlatformTenantsTenantIdIndexRouteImport } from './routes/_platform/tenants/$tenantId/index'
import { Route as AppOrganizationsOrgIdIndexRouteImport } from './routes/_app/organizations/$orgId/index'
import { Route as PlatformTenantsTenantIdMembersRouteImport } from './routes/_platform/tenants/$tenantId/members'
import { Route as AppOrganizationsOrgIdSettingsRouteImport } from './routes/_app/organizations/$orgId/settings'
import { Route as AppOrganizationsOrgIdMembersRouteImport } from './routes/_app/organizations/$orgId/members'

const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const PlatformTenantsIndexRoute = PlatformTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApplicationsAppIdRoute = AppApplicationsAppIdRouteImport.update({
  id: '/applications/$appId',
  path: '/applications/$appId',
  getParentRoute: () => AppRouteRoute,
} as any)
const PlatformTenantsTenantIdIndexRoute =
  PlatformTenantsTenantIdIndexRouteImport.update({
    id: '/tenants/$tenantId/',
    path: '/tenants/$tenantId/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const AppOrganizationsOrgIdIndexRoute =
  AppOrganizationsOrgIdIndexRouteImport.update({
    id: '/organizations/$orgId/',
    path: '/organizations/$orgId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const PlatformTenantsTenantIdMembersRoute =
  PlatformTenantsTenantIdMembersRouteImport.update({
    id: '/tenants/$tenantId/members',
    path: '/tenants/$tenantId/members',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const AppOrganizationsOrgIdSettingsRoute =
  AppOrganizationsOrgIdSettingsRouteImport.update({
    id: '/organizations/$orgId/settings',
    path: '/organizations/$orgId/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationsOrgIdMembersRoute =
  AppOrganizationsOrgIdMembersRouteImport.update({
    id: '/organizations/$orgId/members',
    path: '/organizations/$orgId/members',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/applications/$appId': typeof AppApplicationsAppIdRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/applications/': typeof AppApplicationsIndexRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/tenants/': typeof PlatformTenantsIndexRoute
  '/organizations/$orgId/members': typeof AppOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/settings': typeof AppOrganizationsOrgIdSettingsRoute
  '/tenants/$tenantId/members': typeof PlatformTenantsTenantIdMembersRoute
  '/organizations/$orgId/': typeof AppOrganizationsOrgIdIndexRoute
  '/tenants/$tenantId/': typeof PlatformTenantsTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/callback': typeof AuthCallbackRoute
  '/login': typeof AuthLoginRoute
  '/applications/$appId': typeof AppApplicationsAppIdRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/applications': typeof AppApplicationsIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/tenants': typeof PlatformTenantsIndexRoute
  '/organizations/$orgId/members': typeof AppOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/settings': typeof AppOrganizationsOrgIdSettingsRoute
  '/tenants/$tenantId/members': typeof PlatformTenantsTenantIdMembersRoute
  '/organizations/$orgId': typeof AppOrganizationsOrgIdIndexRoute
  '/tenants/$tenantId': typeof PlatformTenantsTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/applications/$appId': typeof AppApplicationsAppIdRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_platform/tenants/': typeof PlatformTenantsIndexRoute
  '/_app/organizations/$orgId/members': typeof AppOrganizationsOrgIdMembersRoute
  '/_app/organizations/$orgId/settings': typeof AppOrganizationsOrgIdSettingsRoute
  '/_platform/tenants/$tenantId/members': typeof PlatformTenantsTenantIdMembersRoute
  '/_app/organizations/$orgId/': typeof AppOrganizationsOrgIdIndexRoute
  '/_platform/tenants/$tenantId/': typeof PlatformTenantsTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/callback'
    | '/login'
    | '/applications/$appId'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$userId'
    | '/applications/'
    | '/organizations/'
    | '/users/'
    | '/tenants/'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/settings'
    | '/tenants/$tenantId/members'
    | '/organizations/$orgId/'
    | '/tenants/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/callback'
    | '/login'
    | '/applications/$appId'
    | '/settings/profile'
    | '/settings/security'
    | '/users/$userId'
    | '/applications'
    | '/organizations'
    | '/users'
    | '/tenants'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/settings'
    | '/tenants/$tenantId/members'
    | '/organizations/$orgId'
    | '/tenants/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_platform'
    | '/_app/dashboard'
    | '/_auth/callback'
    | '/_auth/login'
    | '/_app/applications/$appId'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/users/$userId'
    | '/_app/applications/'
    | '/_app/organizations/'
    | '/_app/users/'
    | '/_platform/tenants/'
    | '/_app/organizations/$orgId/members'
    | '/_app/organizations/$orgId/settings'
    | '/_platform/tenants/$tenantId/members'
    | '/_app/organizations/$orgId/'
    | '/_platform/tenants/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_platform/tenants/': {
      id: '/_platform/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof PlatformTenantsIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/applications/$appId': {
      id: '/_app/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/applications/$appId'
      preLoaderRoute: typeof AppApplicationsAppIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_platform/tenants/$tenantId/': {
      id: '/_platform/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof PlatformTenantsTenantIdIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_app/organizations/$orgId/': {
      id: '/_app/organizations/$orgId/'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof AppOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_platform/tenants/$tenantId/members': {
      id: '/_platform/tenants/$tenantId/members'
      path: '/tenants/$tenantId/members'
      fullPath: '/tenants/$tenantId/members'
      preLoaderRoute: typeof PlatformTenantsTenantIdMembersRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_app/organizations/$orgId/settings': {
      id: '/_app/organizations/$orgId/settings'
      path: '/organizations/$orgId/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof AppOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/organizations/$orgId/members': {
      id: '/_app/organizations/$orgId/members'
      path: '/organizations/$orgId/members'
      fullPath: '/organizations/$orgId/members'
      preLoaderRoute: typeof AppOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppApplicationsAppIdRoute: typeof AppApplicationsAppIdRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppOrganizationsOrgIdMembersRoute: typeof AppOrganizationsOrgIdMembersRoute
  AppOrganizationsOrgIdSettingsRoute: typeof AppOrganizationsOrgIdSettingsRoute
  AppOrganizationsOrgIdIndexRoute: typeof AppOrganizationsOrgIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppApplicationsAppIdRoute: AppApplicationsAppIdRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppOrganizationsOrgIdMembersRoute: AppOrganizationsOrgIdMembersRoute,
  AppOrganizationsOrgIdSettingsRoute: AppOrganizationsOrgIdSettingsRoute,
  AppOrganizationsOrgIdIndexRoute: AppOrganizationsOrgIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PlatformRouteRouteChildren {
  PlatformTenantsIndexRoute: typeof PlatformTenantsIndexRoute
  PlatformTenantsTenantIdMembersRoute: typeof PlatformTenantsTenantIdMembersRoute
  PlatformTenantsTenantIdIndexRoute: typeof PlatformTenantsTenantIdIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformTenantsIndexRoute: PlatformTenantsIndexRoute,
  PlatformTenantsTenantIdMembersRoute: PlatformTenantsTenantIdMembersRoute,
  PlatformTenantsTenantIdIndexRoute: PlatformTenantsTenantIdIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
